### ISSUE TITLE
Require .edu emails for signup

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/Bookswap#50]
This would validate each user to be a part of a college campus, and open the door to https://github.com/Diogenesthecynic/Bookswap/issues/51.

**Comment by aidielse** [comment]
Just a quick side note that only allowing .edu email addresses would make the log in process less secure because email addresses become easier to brute force where there are constraints on what's allowed. 

example: 

we know that RPI emails are either 6 characters (first 5 from last name, first 1 from first name) or 7 characters (same 6 as before, plus a number). This is much easier to brute force than any email.

Also, RPI keeps a list online (That anyone can access) of all RPI students and their email addresses. Making brute forcing even easier.

Also, what about a student who graduates and then wants to sell their textbooks? They no longer have an rpi.edu email since they are now an alumni. Thus, they would no longer be able to make an account.

Food for thought.

**Comment by JoshuaKGoldberg** [comment]
We could extend this the way GitHub checks for .edu addresses by requiring you to verify a .edu to specify your school, but allow (or even require) an external email for logins & communications.

**Comment by aidielse** [comment]
I was thinking that too.

**Comment by JoshuaKGoldberg** [comment]
For now, https://github.com/Diogenesthecynic/Bookswap/commit/596ef3876fbc1a239725ecbd1c1a1e0e5443f12c just makes sure the user signs up with a school email. We'll have to implement email changing (though edu emails should stay registered to a user in some form) later on.

**Comment by JoshuaKGoldberg** [comment]
Original issue should be fixed in https://github.com/Diogenesthecynic/Bookswap/commit/635f0c58ffaab65ec0056387dc2275c138eb6cf8.
